services:
  worker:
    restart: on-failure
    build: .
    links:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F?heartbeat=600&blocked_connection_timeout=300
      LOG_LEVEL: ${LOG_LEVEL:-info}
      DATABASE_URI: clickhouse:9000
    volumes:
      - ${DATA_ROOT:-.}:/data

  worker-batch-write:
    command: "ftg worker batch -q write-ftm -q write-author-triples"
    restart: on-failure
    build: .
    links:
      - clickhouse
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F?heartbeat=600&blocked_connection_timeout=300
      LOG_LEVEL: ${LOG_LEVEL:-info}
      DATABASE_URI: clickhouse:9000

  rabbitmq:
    image: rabbitmq:management
    restart: on-failure
    expose:
      - 5672
    ports:
      - 127.0.0.1:5672:5672
      - 127.0.0.1:15672:15672
    volumes:
      - ${PWD}/rabbitmq.conf.d:/etc/rabbitmq/conf.d

  clickhouse:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    expose:
      - 9000
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:8123:8123
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
