services:
  worker:
    image: ftg-worker
    links:
      - postgres
      - rabbitmq
      - redis
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F?heartbeat=3600&blocked_connection_timeout=3600
    volumes:
      - ${DATA_ROOT}:/data
    deploy:
      replicas: 48
      resources:
        limits:
          memory: 64G
      restart_policy:
        condition: any
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  worker-psql-ftm:
    command: "ftg worker batch -q write-ftm"
    image: ftg-worker
    links:
      - postgres
      - rabbitmq
      - redis
    environment:
      FTM_STORE_URI: postgresql://ftg:ftg@postgres/ftg
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F?heartbeat=1200&blocked_connection_timeout=600
    deploy:
      replicas: 16
      restart_policy:
        condition: any
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  worker-psql-triples:
    command: "ftg worker batch -q write-author-triples"
    image: ftg-worker
    links:
      - postgres
      - rabbitmq
      - redis
    environment:
      FTM_STORE_URI: postgresql://ftg:ftg@postgres/ftg
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F?heartbeat=1200&blocked_connection_timeout=600
    deploy:
      replicas: 16
      restart_policy:
        condition: any
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:alpine
    command: >
      -c max_connections=500
      -c shared_buffers=46GB
      -c effective_cache_size=138GB
      -c maintenance_work_mem=2GB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=20971kB
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c max_worker_processes=32
      -c max_parallel_workers_per_gather=4
      -c max_parallel_workers=32
      -c max_parallel_maintenance_workers=4
    expose:
      - 5432
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_DB=ftg
      - POSTGRES_USER=ftg
      - POSTGRES_PASSWORD=ftg
    volumes:
      - ${DATA_ROOT}/psql:/var/lib/postgresql/data
    deploy:
      mode: global
      restart_policy:
        condition: any
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ftg"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:management-alpine
    hostname: ftg-rabbit
    environment:
      RABBITMQ_NODENAME: rabbit@ftg-rabbit
    expose:
      - 5672
    ports:
      - 127.0.0.1:8000:15672
    volumes:
      - ${DATA_ROOT}/rabbitmq:/var/lib/rabbitmq
      - ${PWD}/rabbitmq.conf.d:/etc/rabbitmq/conf.d
    deploy:
      mode: global
      restart_policy:
        condition: any
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    expose:
      - 6379
    deploy:
      mode: global
      restart_policy:
        condition: any
