version: '3'

services:
  worker:
    restart: on-failure
    image: ftg-worker-dev
    build: .
    links:
      - postgres
      - rabbitmq
      - redis
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F?heartbeat=600&blocked_connection_timeout=300
      LOG_LEVEL: ${LOG_LEVEL:-info}
    volumes:
      - ${DATA_ROOT}:/data

  worker-psql-ftm:
    command: "ftg worker batch -q write-ftm"
    restart: on-failure
    image: ftg-worker-dev
    build: .
    links:
      - postgres
      - rabbitmq
      - redis
    environment:
      FTM_STORE_URI: postgresql://ftg:ftg@postgres/ftg
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F?heartbeat=600&blocked_connection_timeout=300
      LOG_LEVEL: ${LOG_LEVEL:-info}

  worker-psql-triples:
    command: "ftg worker batch -q write-author-triples"
    restart: on-failure
    image: ftg-worker-dev
    build: .
    links:
      - postgres
      - rabbitmq
      - redis
    environment:
      FTM_STORE_URI: postgresql://ftg:ftg@postgres/ftg
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F?heartbeat=600&blocked_connection_timeout=300
      LOG_LEVEL: ${LOG_LEVEL:-info}

  postgres:
    restart: on-failure
    image: postgres:alpine
    expose:
      - 5432
    ports:
      - 54321:5432
    environment:
      - POSTGRES_DB=ftg
      - POSTGRES_USER=ftg
      - POSTGRES_PASSWORD=ftg

  rabbitmq:
    restart: on-failure
    image: rabbitmq:management-alpine
    expose:
      - 5672
    ports:
      - 8000:15672
    volumes:
      - ${PWD}/rabbitmq.conf.d:/etc/rabbitmq/conf.d

  redis:
    restart: on-failure
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
