services:
  worker:
    image: ghcr.io/followthegrant/followthegrant:main
    links:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F?heartbeat=3600&blocked_connection_timeout=3600
      LOG_LEVEL: ${LOG_LEVEL:-info}
    volumes:
      - ${DATA_ROOT}:/data
    deploy:
      replicas: 48
      resources:
        limits:
          memory: 64G
      restart_policy:
        condition: any
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker-batch-write:
    image: ghcr.io/followthegrant/followthegrant:main
    command: "ftg worker batch -q write-ftm -q write-author-triples"
    links:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F?heartbeat=1200&blocked_connection_timeout=600
      LOG_LEVEL: ${LOG_LEVEL:-info}
      DATABASE_URI: clickhouse:9000
    deploy:
      replicas: 8
      restart_policy:
        condition: any
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:management
    hostname: ftg-rabbit
    environment:
      RABBITMQ_NODENAME: rabbit@ftg-rabbit
    expose:
      - 5672
    ports:
      - 127.0.0.1:15672:15672
    volumes:
      - ${DATA_ROOT}/rabbitmq:/var/lib/rabbitmq
      - ${PWD}/rabbitmq.conf.d:/etc/rabbitmq/conf.d
    deploy:
      mode: global
      restart_policy:
        condition: any
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    expose:
      - 9000
    ports:
      - 127.0.0.1:9000:9000
      - 127.0.0.1:8123:8123
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ${DATA_ROOT}/clickhouse-data:/var/lib/clickhouse
